version: "3.0"

services:
  database:
    image: docker.io/library/mariadb:latest
    environment:
      - MYSQL_DATABASE=podman
      - MYSQL_USER=lebo
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
    - 3312:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: