FROM mysql:8.0

# Define build arguments
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG TZ

ENV MYSQL_DATABASE=practice
ENV TZ=Africa/Pretoria

# Set timezone
RUN ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime

# Add persistent storage
VOLUME /var/lib/mysql

# Custom MySQL configuration
COPY ./my.cnf /etc/mysql/conf.d/

# Expose MySQL port
EXPOSE 3306

CMD ["mysqld"]